### ISSUE TITLE
jq version dependency

### ISSUE THREAD

**Issue by SachinCldCvr** [varunchandak/automate-launch-configuration-update-with-latest-image#1]
jq version should be more than 1.6 to run this script as `walk` is not working with < jq-1.6
jq-1.6 is available on greater version of ubuntu-16.04 

to get jq version 1.6 for ubuntu
```
wget 'https://github.com/stedolan/jq/releases/download/jq-1.6/jq-linux64'
```

**Comment by varunchandak** [comment]
Thanks for the issue. Let me get the script updated properly to work with the correct version of `jq`.

**Comment by varunchandak** [comment]
So as to not mess up existing `jq`, I'd recommend downloading the binary independently and alias it in the script.
```
wget 'https://github.com/stedolan/jq/releases/download/jq-1.6/jq-linux64' -P /tmp/
alias jq='/tmp/jq-linux64'
```

**Comment by SachinCldCvr** [comment]
Yes, that would also help without messing up the current version of `jq`.
