### ISSUE TITLE
Issue while launching new instances in ASG with new LC created by this script

### ISSUE THREAD

**Issue by SachinCldCvr** [varunchandak/automate-launch-configuration-update-with-latest-image#3]
I am getting below error while launching the new instance in Auto Scaling Group with this launch config.
```
Launching a new EC2 instance. Status Reason: snapshotId cannot be modified on root device. Launching EC2 instance failed.
```

**Comment by varunchandak** [comment]
Thanks for this. Apparently, the script was using the old snapshots in the block device mappings in the LC, but with new AMI ID. I have removed the `BlockDeviceMappings` block from the launch configuration.
