### ISSUE TITLE
additional optional parameter of Instance Id

### ISSUE THREAD

**Issue by SachinCldCvr** [varunchandak/automate-launch-configuration-update-with-latest-image#4]
Can we also have one more parameter of instance Id in this script, like below

`./automate-launch-configuration-update-with-latest-image.sh <AWS_PROFILE> <AWS_REGION> <ASG_NAME> <InstanceId>`

The reason behind this is - Many times we need to make some configurations changes to the instance and update the LC with the AMI of that instance, which can be used as golden image. This feature will help a lot in implementing this case.

We can achieve this in this way - If the InstanceId parameter is there then it will pick that instance to create the AMI and if it is not passed then it can pick a random instance from the ASG as it is doing right now.

**Comment by varunchandak** [comment]
Interesting ! Let me check it out.

**Comment by varunchandak** [comment]
@SachinCldCvr made some changes. Please test that out and let me know in case of any issues.
