### ISSUE TITLE
I getting the below error. Please can you help me to get it fixed

### ISSUE THREAD

**Issue by smartkriash** [varunchandak/automate-launch-configuration-update-with-latest-image#5]
[root@ip-10-0-24-11 ec2-user]# ./autoscaling-update.sh awsopsrd ap-south-1 Autoscaling-Test-New-ASG i-049654863a20dd53f
Using i-049654863a20dd53f instead of random instance.
AMI creation still under progress. Retrying in 15 seconds...
AMI creation still under progress. Retrying in 15 seconds...
AMI creation still under progress. Retrying in 15 seconds...
jq: error: walk/1 is not defined at <top-level>, line 1:
walk(if type == "object" then with_entries(select(.value != null and .value != "" and .value != [] and .value != {} and .value != [""] )) else . end )
jq: 1 compile error

Error parsing parameter 'cli-input-json': Invalid JSON: No JSON object could be decoded
JSON received:

An error occurred (ValidationError) when calling the UpdateAutoScalingGroup operation: Launch configuration name not found - A launch configuration with the name: Autoscaling-Test-New-25012020 does not exist

**Comment by smartkriash** [comment]
@varunchandak , can you please help me in getting the above issue resolve

**Comment by varunchandak** [comment]
@smartkriash what's your `jq` version ?

**Comment by misawsneto** [comment]
jq version is jq-1.5-1-a5b5cbe

**Comment by varunchandak** [comment]
closed for inactivity.
