### ISSUE TITLE
Block devices value is coming empty while creating new launch configuration.

### ISSUE THREAD

**Issue by altif227** [varunchandak/automate-launch-configuration-update-with-latest-image#6]
Hi Varun,

Thank a lot for sharing the script. Everything is working fine as expected but while creating new launch configuration, Block devices values is showing empty while checking in AWS Console. Can you please help me on this? Attaching SS for reference.
![Screenshot from 2020-05-31 18-34-59](https://user-images.githubusercontent.com/40140437/83353062-836ddf00-a36d-11ea-9bfb-5bbf43d5c08b.png)

Regards,
Altif

**Comment by varunchandak** [comment]
That should be fine as the AMI contains the block device mappings already. Are you facing any issues on launching instances using this launch config ?

**Comment by altif227** [comment]
Hi @varunchandak,
Thank you for the response. Instance provisioning is getting failed due to missing block devices. Even block device value is missing in /tmp/"$NEW_LC_NAME".json file as well. If I use same AMI  to create launch configuration from AWS Console, it does work fine. SS for reference.

Thanks,
Altif
![Screenshot from 2020-06-01 00-27-17](https://user-images.githubusercontent.com/40140437/83360443-f5125100-a39e-11ea-8485-535aa629607b.png)

**Comment by varunchandak** [comment]
can you tell me your block device mappings associated with the AMI ?

**Comment by altif227** [comment]
@varunchandak Apology for the trouble, I've tested again and it worked fine, couldn't find out what I was missing.  Thanks a lot... :)

Regards,
Altif
